### ISSUE TITLE
`brakeman_flags` should be passed as separate strings to `brakeman`

### ISSUE THREAD

**Issue by dgholz** [reviewdog/action-brakeman#30]
Setting `brakeman_flags` to `--config-file ./config/brakeman.yml`, the action runs and fails with:
```
  invalid option: --config-file ./config/brakeman.yml
```
https://github.com/dgholz/reviewdog-brakeman/runs/4470451313?check_suite_focus=true#step:4:35

It's because the options are quoted in https://github.com/reviewdog/action-brakeman/blob/3073c89bf52f7e1a5ab4ba2d5bfc88815311c131/script.sh#L40, so they get passed as a single option

**Comment by ybiquitous** [comment]
Hi, I'm having trouble with this behavior too. 😢 

```yaml
brakeman_flags: '--no-exit-on-warn --no-exit-on-error'
```

![image](https://user-images.githubusercontent.com/473530/148902531-6e687d1a-5296-49ce-9423-41279d96d24d.png)

**Comment by ybiquitous** [comment]
Thank you for the quick fix! 😄
