### ISSUE TITLE
Feature request: run `brakeman` with Bundler

### ISSUE THREAD

**Issue by dgholz** [reviewdog/action-brakeman#32]
With the new composite action, we have to explicitly install Ruby. Dev who want to use Brakeman are extremely likely to be very familiar with `ruby/setup-ruby` and will want to install their dependencies from the Gemfile & [take advantage of the action's caching support](https://github.com/ruby/setup-ruby#caching-bundle-install-automatically):
```
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
```
The script ignores the installed bundle and reinstalls the gem; fortunately, Gem is smart and sees it's already installed. But it would be nice to skip over the version checking and installing if the gem is already available in the bundle.

**Comment by mgrachev** [comment]
Available in [v2.7.0](https://github.com/reviewdog/action-brakeman/releases/tag/v2.7.0).
